apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-vm-template
  title: Azure Virtual Machine
  description: Create an Azure VM with infrastructure as code
  tags:
    - azure
    - vm
    - infrastructure
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: Project Information
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the VM
        description:
          title: Description
          type: string
          description: Purpose of this virtual machine
        owner:
          title: Owner
          type: string
          description: Owner of the VM
          default: team-a
    - title: Repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
    - title: VM Configuration
      required:
        - vmSize
        - osType
      properties:
        vmSize:
          title: VM Size
          type: string
          default: "Standard_B2s"
          enum: ["Standard_B1s", "Standard_B2s", "Standard_D2s_v3"]
        osType:
          title: Operating System
          type: string
          default: "Ubuntu"
          enum: ["Ubuntu", "Windows", "CentOS"]
        adminUsername:
          title: Admin Username
          type: string
          default: "azureuser"
    - title: Azure Configuration
      required:
        - azureSubscription
        - resourceGroup
      properties:
        azureSubscription:
          title: Azure Subscription
          type: string
          description: Azure subscription ID
        resourceGroup:
          title: Resource Group
          type: string
          description: Azure resource group name
  steps:
    - id: fetch
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          vmSize: ${{ parameters.vmSize }}
          osType: ${{ parameters.osType }}
          adminUsername: ${{ parameters.adminUsername }}
          azureSubscription: ${{ parameters.azureSubscription }}
          resourceGroup: ${{ parameters.resourceGroup }}
    - id: publish
      name: Publish
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}